apiVersion: v1
kind: Namespace
metadata:
  name: logicapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logicapp
  name: logicapp
  namespace: logicapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logicapp
  template:
    metadata:
      labels:
        app: logicapp
    spec:
      containers:
      - image: <<your_docker-image_url>>
        name: logicapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: AzureWebJobsStorage
          value: <<your_azure-storage-account_connectionstring>>
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
    name: logicapp
    namespace: logicapp
    labels:
        app: logicapp
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: logicapp
